version: '3'
services:
  op-db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  op-kv:
    image: redis:7.2.5-alpine
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --maxmemory-policy noeviction --notify-keyspace-events AKE
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  op-geo:
    image: observabilitystack/geoip-api:latest
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  op-ch:
    image: clickhouse/clickhouse-server:24.3.2-alpine
    restart: always
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
      - ./self-hosting/clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/op-config.xml:ro
      - ./self-hosting/clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/op-user-config.xml:ro
      - ./self-hosting/clickhouse/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_DB=openpanel
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  openpanel:
    image: ${COOLIFY_IMAGE_NAME:-jojovvz/openpanel:main}
    restart: always
    depends_on:
      op-db:
        condition: service_healthy
      op-kv:
        condition: service_healthy
      op-ch:
        condition: service_healthy
      op-geo:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://op-kv:6379
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@op-db:5432/${DB_NAME}?schema=public
      - DOMAIN=${COOLIFY_FQDN}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION:-false}
      - ALLOW_INVITATION=${ALLOW_INVITATION:-true}
      - NEXT_PUBLIC_DASHBOARD_URL=https://${COOLIFY_FQDN}
      - NEXT_PUBLIC_API_URL=https://${COOLIFY_FQDN}/api
      - WORKER_PORT=9999
      - API_PORT=3333
      - BATCH_SIZE=5000
      - BATCH_INTERVAL=10000
      - CONCURRENCY=10
    volumes:
      - app_data:/app/data
      - selfhosting_data:/app/self-hosting/data
      - logs:/app/logs

volumes:
  db_data:
  redis_data:
  clickhouse_data:
  clickhouse_logs:
  app_data:
  selfhosting_data:
  logs:
