version: '3'
services:
  op-db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - type: bind
        source: /data/coolify/applications/${COOLIFY_APP_ID}/storage/op-db-data
        target: /var/lib/postgresql/data
        is_directory: true
    environment:
      - POSTGRES_USER=${SERVICE_USER_POSTGRES}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - SERVICE_FQDN_POSTGRES_5432
    ports:
      - "${PORT_DB:-5432}:5432"

  op-kv:
    image: redis:7.2.5-alpine
    restart: always
    volumes:
      - type: bind
        source: /data/coolify/applications/${COOLIFY_APP_ID}/storage/op-kv-data
        target: /data
        is_directory: true
    command: ['redis-server', '--maxmemory-policy', 'noeviction']
    environment:
      - REDIS_PASSWORD=${SERVICE_PASSWORD_REDIS}
      - SERVICE_FQDN_REDIS_6379
    ports:
      - "${PORT_REDIS:-6379}:6379"

  op-geo:
    image: observabilitystack/geoip-api:latest
    restart: always
    environment:
      - SERVICE_FQDN_GEOIP=/api
      - SERVICE_URL_GEOIP
      - HOST=0.0.0.0
      - PORT=${PORT_GEO:-8081}
      - JAVA_OPTS=-Xmx512m -Djava.security.egd=file:/dev/./urandom
    ports:
      - "${PORT_GEO:-8081}:8080"
    volumes:
      - type: bind
        source: /data/coolify/applications/${COOLIFY_APP_ID}/config/geoip
        target: /srv
        is_directory: true

  op-ch:
    image: clickhouse/clickhouse-server:24.3.2-alpine
    restart: always
    volumes:
      - type: bind
        source: /data/coolify/applications/${COOLIFY_APP_ID}/storage/op-ch-data
        target: /var/lib/clickhouse
        is_directory: true
      - type: bind
        source: /data/coolify/applications/${COOLIFY_APP_ID}/storage/op-ch-logs
        target: /var/log/clickhouse-server
        is_directory: true
      - type: bind
        source: /data/coolify/applications/${COOLIFY_APP_ID}/config/clickhouse/config.xml
        target: /etc/clickhouse-server/config.xml
        content: |
          <?xml version="1.0"?>
          <clickhouse>
              <logger>
                  <level>warning</level>
                  <console>true</console>
                  <log>/var/log/clickhouse-server/clickhouse-server.log</log>
                  <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
              </logger>

              <http_port>${PORT_CH_HTTP:-8124}</http_port>
              <tcp_port>${PORT_CH_TCP:-9001}</tcp_port>
              <interserver_http_port>${PORT_CH_INTER:-9010}</interserver_http_port>

              <listen_host>0.0.0.0</listen_host>
              
              <path>/var/lib/clickhouse/</path>
              <tmp_path>/var/lib/clickhouse/tmp/</tmp_path>
              
              <users_config>users.xml</users_config>
              <default_profile>default</default_profile>
              <default_database>default</default_database>
              
              <mark_cache_size>5368709120</mark_cache_size>
              <max_concurrent_queries>100</max_concurrent_queries>
          </clickhouse>
      - type: bind
        source: /data/coolify/applications/${COOLIFY_APP_ID}/config/clickhouse/users.xml
        target: /etc/clickhouse-server/users.xml
        content: |
          <?xml version="1.0"?>
          <clickhouse>
              <users>
                  <default>
                      <password>${SERVICE_PASSWORD_CLICKHOUSE}</password>
                      <networks>
                          <ip>::/0</ip>
                          <ip>0.0.0.0/0</ip>
                      </networks>
                      <profile>default</profile>
                      <quota>default</quota>
                  </default>
              </users>
              
              <profiles>
                  <default>
                      <max_memory_usage>10000000000</max_memory_usage>
                      <max_memory_usage_for_user>10000000000</max_memory_usage_for_user>
                      <max_bytes_before_external_group_by>20000000000</max_bytes_before_external_group_by>
                  </default>
              </profiles>

              <quotas>
                  <default>
                      <interval>
                          <duration>3600</duration>
                          <queries>0</queries>
                          <query_selects>0</query_selects>
                          <query_inserts>0</query_inserts>
                          <errors>0</errors>
                          <result_rows>0</result_rows>
                          <read_rows>0</read_rows>
                          <execution_time>0</execution_time>
                      </interval>
                  </default>
              </quotas>
          </clickhouse>
    environment:
      - SERVICE_FQDN_CLICKHOUSE
      - CLICKHOUSE_PASSWORD=${SERVICE_PASSWORD_CLICKHOUSE}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "${PORT_CH_HTTP:-8124}:8124"
      - "${PORT_CH_TCP:-9001}:9001"
      - "${PORT_CH_INTER:-9010}:9010"
